generate_game_logic:
  description: >
    Write core JavaScript logic for a dynamic dark maze game called "Shifting Shadows".
  expected_output: >
    JavaScript file with modular functions for maze generation, torchlight, key collection, and re-randomization.
  output_file: game_outputs/game_logic.js
  agent: game_logic_agent

design_ui_ux:
  description: >
    Create a responsive UI for the game, including main menu, settings, HUD, and game over screen.
  expected_output: >
    HTML and CSS layout with mobile-first design principles.
  context: ["generate_game_logic"]
  output_file: game_outputs/ui_ux.html
  agent: ui_ux_agent

handle_input_controls:
  description: >
    Implement input handling for both keyboard and mobile touch devices.
  expected_output: >
    JavaScript input module compatible with canvas-based movement.
  context: ["generate_game_logic", "design_ui_ux"]
  output_file: game_outputs/input_control.js
  agent: user_input_agent

integrate_code_modules:
  description: >
    Combine code from all agents into one runnable HTML5 game file.
  expected_output: >
    A single HTML file with all components integrated and working.
  context: ["generate_game_logic", "design_ui_ux", "handle_input_controls"]
  output_file: game_outputs/code_integrated.html
  agent: code_integrator_agent

test_and_debug_game:
  description: >
    Review the full HTML game code, identify issues, and fix errors in logic or layout.
  expected_output: >
    Final polished HTML5 file with no bugs and fully playable logic.
  context: ["integrate_code_modules"]
  output_file: game_outputs/final_game.html
  agent: tester_debugger_agent
